app = "mutual-fund-bot"  # Change this if you've picked a different app name on Fly

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "TRUE"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
